spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

logging:
  level:
    org.springframework.r2dbc.core: debug

jwt:
  secret: test