spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: root

  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always

logging:
  level:
    org.springframework.r2dbc.core: debug

jwt:
  secret: test